---
title: "My Portfolio - Alice Bourne"
description: " Portfolio of both personal and university projects | 
  MBiolSci Biology graduate, The University of Sheffield (2020-2024), with an aptitude for data science |  
  MSc Applied Bioinformatics student, KCL (2025-2026), preparing for a computational research career " 
theme: jekyll-theme-minimal
logo: "/logo.jpg"
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
---


