---
title: "My Portfolio - Alice Bourne"
description: ""
theme: jekyll-theme-minimal
show_downloads: [true]
logo: "/logo.jpg"
plugins:
  - jekyll-feed
---

# Connect with me

[Email](mailto:alicebourne279@gmail.com) | [LinkedIn](https://www.linkedin.com/in/alice-bourne-b704b3223)  
