---
title: "My Portfolio - Alice Bourne"
description: "I have a background in palaeontology, botany, and data science, earning an MBiolSci in Biology from Sheffield (2020–2024). Now, I'm pursuing an MSc in Applied Bioinformatics at King's College London (2025–2026) to apply my computational skills in medical research."
theme: jekyll-theme-minimal
show_downloads: [true]
logo: "/logo.jpg"
plugins:
  - jekyll-feed
---

# Connect with me

[Email](mailto:alicebourne279@gmail.com) | [LinkedIn](https://www.linkedin.com/in/alice-bourne-b704b3223)  
