---
title: "My Portfolio - Alice Bourne"
description: "I'm a passionate scientist with a background in palaeontology, botany, and bioinformatics. I earned an MBiolSci in Biology from the University of Sheffield (2020–2024), where I developed a strong aptitude for data science and R programming. Now, I'm transitioning into medical bioinformatics, pursuing an MSc in Applied Bioinformatics at King's College London (2025–2026). My goal is to work in research, combining my scientific and computational skills to drive discoveries"
theme: jekyll-theme-minimal
show_downloads: [true]
logo: "/logo.jpg"
plugins:
  - jekyll-feed
---

# Connect with me

[Email](mailto:alicebourne279@gmail.com) | [LinkedIn](https://www.linkedin.com/in/alice-bourne-b704b3223)  
