---
title: "My Portfolio - Alice Bourne"
description: " Portfolio of both personal and university projects | 
  MBiolSci Biology graduate, The University of Sheffield (2020-2024), with an aptitude for data science |  
  MSc Applied Bioinformatics student, KCL (2025-2026), preparing for a computational research career " 
theme: jekyll-theme-minimal
logo: "/logo.jpg"
permalink: pretty
markdown: kramdown
collections:
  projects:
    output: true
plugins:
  - jekyll-feed
  email: "alicebourne279@gmail.com"
linkedin: "https://www.linkedin.com/in/alice-bourne-b704b3223"
---

